// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFN.Sign.Infrastructure.Persistence;

#nullable disable

namespace SFN.Sign.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SignDbContext))]
    [Migration("20260828094328_AddTemplateValuesToSignRequest")]
    partial class AddTemplateValuesToSignRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sign")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SFN.Sign.Domain.Entities.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TemplateType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TemplateType");

                    b.HasIndex("Channel", "IsActive");

                    b.ToTable("MessageTemplates", "sign");
                });

            modelBuilder.Entity("SFN.Sign.Domain.Entities.SignAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SignRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SignRequestId");

                    b.ToTable("SignAttempts", "sign");
                });

            modelBuilder.Entity("SFN.Sign.Domain.Entities.SignCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CodeSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SignRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SignRequestId")
                        .IsUnique();

                    b.HasIndex("SignRequestId", "IsUsed");

                    b.ToTable("SignCodes", "sign");
                });

            modelBuilder.Entity("SFN.Sign.Domain.Entities.SignRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentSignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("SendAttemptsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("VerifyAttemptsUsed")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DocumentSignId");

                    b.HasIndex("Status");

                    b.ToTable("SignRequests", "sign");
                });

            modelBuilder.Entity("SFN.Sign.Domain.Entities.SignAttempt", b =>
                {
                    b.HasOne("SFN.Sign.Domain.Entities.SignRequest", "SignRequest")
                        .WithMany("SignAttempts")
                        .HasForeignKey("SignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignRequest");
                });

            modelBuilder.Entity("SFN.Sign.Domain.Entities.SignCode", b =>
                {
                    b.HasOne("SFN.Sign.Domain.Entities.SignRequest", "SignRequest")
                        .WithOne("SignCode")
                        .HasForeignKey("SFN.Sign.Domain.Entities.SignCode", "SignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignRequest");
                });

            modelBuilder.Entity("SFN.Sign.Domain.Entities.SignRequest", b =>
                {
                    b.Navigation("SignAttempts");

                    b.Navigation("SignCode");
                });
#pragma warning restore 612, 618
        }
    }
}
